SELECT REA.RID, REA.RNAME, COUNT(DISTINCT BOR.DOCID)
    FROM READER AS REA, BORROWS AS BOR
    WHERE BOR.RID = REA.RID AND BOR.DOCID IN (
      SELECT DISTINCT DOCID
        FROM BOOK
    ) AND BOR.BID='6002'
    GROUP BY REA.RID
    ORDER BY COUNT(DISTINCT BOR.DOCID) DESC
    LIMIT 10;